server:
  port: 8080

logging:
  level:
    root: INFO
    com.demosso.authorizationserver: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  datasource:
    url: jdbc:postgresql://localhost:5442/demosso-state
    username: demosso
    password: password
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      connection-test-query: "SELECT 1"
      connectionTimeout: 30000
      validation-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      auto: none

  flyway:
    url: jdbc:postgresql://localhost:5442/demosso-state
    user: demosso
    password: password


ctp:
  auth:
    hash:
      strength: 4


com:
  auth0:
    domain: dev-hhahrzni3t6tv1sl.eu.auth0.com
    clientId: 3gkosK6YUED1XpxWRLzBCovQkngj7WDD
    clientSecret: Z7X_BThrQZ0AOLAwAGOqTqwGe2BoJMqrEE72ypf85jJnNjAQYDY9gtTUxZZEXvex
    managementApi:
      clientId: uxpXPEpZRRfjufbMlw9DGMZrATHJvcGs
      clientSecret: -iwkZt1IIp97a8kod_iubqCD4cIDO2K49p2U88N4Of6ZyC6KMdcricAr5-pZL8z8
      grantType: client_credentials